# Generated by Django 4.2 on 2023-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogpost_thummnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='thummnails',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
